version: 2
jobs:
  build_demo:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-angular-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - /node_modules
          key: v2-dependencies-angular-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Test
          command: |
            yarn test:ci
      # - run:
      #       name: Build Demo
      #       command: |
      #           yarn build

workflows:
  version: 2
  angular_demo:
    jobs:
      - build_demo
